// Service worker registration (production builds only) and the "new content
// available" signal. The worker itself is generated by build/pwa-plugin.ts.
import { useSyncExternalStore } from "react";
import { pageDomain } from "./route.ts";

let waiting: ServiceWorker | null = null;
let reloadRequested = false;
const listeners = new Set<() => void>();
const setWaiting = (w: ServiceWorker | null) => {
  waiting = w;
  listeners.forEach((l) => l());
};

export function registerServiceWorker() {
  if (!import.meta.env.PROD || !("serviceWorker" in navigator)) return;
  const sw = navigator.serviceWorker;
  // sw.js sits at the app root, one level above the domain pages.
  sw.register((pageDomain ? "../" : "./") + "sw.js")
    .then((reg) => {
      // An update is "ready" when a new worker installed while an old one controls the page.
      const ready = (w: ServiceWorker | null) => {
        if (w?.state === "installed" && sw.controller) setWaiting(w);
      };
      ready(reg.waiting);
      reg.addEventListener("updatefound", () => {
        const w = reg.installing;
        w?.addEventListener("statechange", () => ready(w));
      });
      // Long-lived tabs: look for new content when the app comes back into view.
      document.addEventListener("visibilitychange", () => {
        if (document.visibilityState === "visible")
          reg.update().catch(() => {});
      });
    })
    .catch(() => {}); // No offline support, the app still works online.
  sw.addEventListener("controllerchange", () => {
    if (reloadRequested) location.reload();
  });
}

/** Activates the waiting worker; the page reloads once it takes control. */
export function applyUpdate() {
  reloadRequested = true;
  waiting?.postMessage("skip-waiting");
}

export const dismissUpdate = () => setWaiting(null);

export const useUpdateReady = () =>
  useSyncExternalStore(
    (cb) => {
      listeners.add(cb);
      return () => listeners.delete(cb);
    },
    () => waiting !== null,
  );
